POST http://localhost:9090/register HTTP/1.1
Content-Type: application/json

{
  "username": "aryan",
  "name": "aryan",
  "email": "aryan@gmail.com",
  "password": "1234",
  "role": "freelancer"
}
    
###
POST http://localhost:9090/register HTTP/1.1
Content-Type: application/json

{
  "name": "natik",
  "username": "natik01",
  "email": "natik@gmail.com",
  "password": "1234",
  "role": "client"
}

###

POST http://localhost:9090/login HTTP/1.1
Content-Type: application/json

{
   "email":"aryan@gmail.com",
   "password":"1234"
}    

 

###
POST http://localhost:9090/login HTTP/1.1
Content-Type: application/json

{
   "email":"natik@gmail.com",
   "password":"1234"
}  


###
GET http://localhost:9090/freelancers/my_profile
Content-Type: application/json
Cookie: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZmYyNTU1OGQzOGIxMzY4MjQ2ZDk2OCIsImlhdCI6MTc3ODMyODkyNiwiZXhwIjoxNzc4OTMzNzI2fQ.zeCaA1xrwX4CH-zt3osin0vBRUpnYGxEsQf2aGKUHE8

###
PUT http://localhost:9090/freelancers/update_profile HTTP/1.1
Content-Type: application/json
Cookie:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZmNjZjVhZDE0MGUwYTgwMzc4YTI1MyIsImlhdCI6MTc3ODMyNzc1MiwiZXhwIjoxNzc4OTMyNTUyfQ.nFPB-slruzezBoNiw4M-dOCvm6FNYWbME7Ag-0HF4xo

{
  "title": "Full Stack Developer",
  "bio": "MERN Stack Developer",
  "hourRate": 20,
  "location": "India"
}

###
GET http://localhost:9090/freelancers/all
Content-Type: application/json
 
###
 POST http://localhost:9090/jobs/create
Content-Type: application/json
Cookie:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZmY1ZjE5NWFhNTg1NGFiYzQ5ZGNiMCIsImlhdCI6MTc3ODM0MzcxMSwiZXhwIjoxNzc4OTQ4NTExfQ.Iie14MbWnYB0GZCffBfV1_ixnD2GpwzVwOkYbrOg40g

{
  "title": "MERN Developer",
  "description": "Need full stack dev",
  "budget": 500,
  "skillsRequired": ["React", "Node.js"],
  "deadline": "2026-06-01"
}