 POST http://localhost:9090/register HTTP/1.1
 Content-Type: application/json

 {
    "username":"aryan",
    "password":"1234",
     "email":"aryan@gmail.com",
    "name":"aryan"
    }

    
###

POST http://localhost:9090/login HTTP/1.1
Content-Type: application/json

{
   "email":"aryan@gmail.com",
   "password":"1234"
}    

###

POST http://localhost:9090/login HTTP/1.1
Content-Type: application/json

{
   "email":"natik@gmail.com",
   "password":"1234"
}  


###
GET http://localhost:9090/freelancers/my_profile
Content-Type: application/json
Cookie: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZmNjZjVhZDE0MGUwYTgwMzc4YTI1MyIsImlhdCI6MTc3ODMyNzk1MywiZXhwIjoxNzc4OTMyNzUzfQ.2TMuoNMqmMPqA66lWCsxoaI843Nixv4dLKoGRcN-dDs

###
PUT http://localhost:9090/freelancers/update_profile HTTP/1.1
Content-Type: application/json
Cookie:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZmNjZjVhZDE0MGUwYTgwMzc4YTI1MyIsImlhdCI6MTc3ODMyNzc1MiwiZXhwIjoxNzc4OTMyNTUyfQ.nFPB-slruzezBoNiw4M-dOCvm6FNYWbME7Ag-0HF4xo

{
  "title": "Full Stack Developer",
  "bio": "MERN Stack Developer",
  "hourRate": 20,
  "location": "India"
}